### ISSUE TITLE
devenv: Failed to run command

### ISSUE THREAD

**Issue by MPietrukowski** [run-as-root/rooter#12]
Hello... I'm trying to setup Magento 2 with rooter. I'm getting below error on `direnv allow` step. 

```direnv: loading ~/Sites/cmt/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/95f329d49a8a5289d31e0982652f7058a189bfca/direnvrc (sha256-d+8cBpDfDBj41inrADaJt+bDWhOktwslgoP5YiGJ1v0=)
direnv: using devenv
direnv: .envrc changed, reloading
• Using Cachix: devenv
Error:   × Failed to run command `/nix/store/m16x8dlzwhp7sx570h82h3x5332ldbfs-nix-2.24-devenv/bin/nix --show-trace --extra-experimental-features nix-command --extra-experimental-features flakes --option warn-dirty false --keep-going --max-jobs 6 --option eval-cache false --option extra-
  │ substituters https://devenv.cachix.org --option extra-trusted-public-keys devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= print-dev-env --profile /Users/mariusz/Sites/cmt/.devenv/gc/shell -vv --log-format internal-json`
  ╰─▶ Nix command failed: signal: 11 (SIGSEGV)

direnv: failed to build the devenv environment. devenv.nix may contain errors. see above.
direnv: export +DEVENV_AMQP_MANAGEMENT_PORT +DEVENV_AMQP_PORT +DEVENV_DB_PORT +DEVENV_HTTPS_PORT +DEVENV_HTTP_PORT +DEVENV_MAIL_SMTP_PORT +DEVENV_MAIL_UI_PORT +DEVENV_OPENSEARCH_PORT +DEVENV_OPENSEARCH_TCP_PORT +DEVENV_PROCESS_COMPOSE_PORT +DEVENV_REDIS_PORT +NIXPKGS_ALLOW_INSECURE +ROOTER_ENV_TYPE```

**Comment by mwr** [comment]
Hi @MPietrukowski 

Could you share which versions for nix and devenv you are using?

```
nix --version
devenv version
```

Based on the error message I am assuming its nix 2.24, devenv is unclear though.

With the recent devenv 1.2 and 1.3 release some changes were introduced.  
I am working on updating the templates.

**Comment by MPietrukowski** [comment]
Hi @mwr 
Thanks for replaying to this issue. I really want it to work, It's a fantastic project.

```
nix (Nix) 2.24.9
devenv 1.3.0 (aarch64-darwin)
```

**Comment by mwr** [comment]
Hi @MPietrukowski 

I just pushed a release that contains updated versions of the templates. 
I have been using them already, but never updated the templates 🫠 

For your environment it would be best to start clean:
- remove .devenv directory
- remove .direnv directory
- run `rooter env:create magento2 --force`

This will overwrite the .env, devenv.nix and devenv.yaml files with a fresh copy of the template.

If it still does not work we need to look somewhere else.

**Comment by MPietrukowski** [comment]
upgrade to rooter version 1.0.0-beta8 resolved my issue. Many Thanks @mwr

**Comment by mwr** [comment]
Great then I am closing this issue
